config/routes.rb
Leposse::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :venues
  resources :games
  resources :search

  match "/about" => "pages#about", as: :about
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/games/:id/join" => "games#join", as: :join
  get "/games/:id/leave" => "games#leave", as: :leave
  get "/user/:id/show" => "users#show", as: :user
  get "/users" => "users#index", as: :users
  get "/search/:query" => "searches#show", as: :search


  root to: "pages#home"
end

app/views/partials/_navbar.html.erb
<div class="container navbar-wrapper">
  <div class="navbar">
    <div class="navbar-inner">
      <a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-chevron-down"></span>
      </a>
      <a class="brand" href="/">lePosse</a>
      <div class="nav-collapse collapse" style="height: 0px;">
        <ul class="nav">
          <li><%=link_to "Home", root_path%></li>
          <li><%=link_to "About", about_path%></li>
          <li><%=link_to "Games", games_path%></li>
          <li><%=link_to "Users", users_path%></li>
        </ul>
        <ul class="nav pull-right">

          <% if current_user.present? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.first_name + ' ' + current_user.last_name %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/users/edit">Edit Account</a></li>
              <li><%= link_to('Sign Out', destroy_user_session_path, method: "delete") %> </li>
            </ul>
          </li>
          <% else %>
          <li><a href="/users/sign_up">Sign Up</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In<b class="caret"></b></a>
            <ul class="dropdown-menu" id="sign_in">
              <%= form_for("user", :url => user_session_path, html: {class: "dropdown-input"}) do |f| %> 
              <%= f.text_field :email , :size=>'15',:maxlength=>'32', placeholder: "Email"%> <br/> 
              <%= f.password_field :password , :size=>'15', :maxlength=>'32', placeholder: "Password"%><br/> 
              <%= f.submit "Sign in", class: "btn btn-primary" %>
              <%= link_to "Facebook Login", user_omniauth_authorize_path(:facebook), class: "btn input-btn" %>
              <% end %> 
            </ul>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>