config/routes.rb
Leposse::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :venues
  resources :games
  resources :search

  match "/about" => "pages#about", as: :about
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/games/:id/join" => "games#join", as: :join
  get "/games/:id/leave" => "games#leave", as: :leave
  get "/user/:id/show" => "users#show", as: :user
  get "/users" => "users#index", as: :users
  get "/search/:query" => "searches#show", as: :search


  root to: "pages#home"
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :date, :details, :end_time, :host_id, :maxpax, :sport_id, :start_time, :venue_id, :title
  belongs_to :venue
  belongs_to :sport
  has_and_belongs_to_many :users, uniq: true

  validates :date, :end_time, :host_id, :maxpax, :sport_id, :start_time, :venue_id, :title, presence: true
  validate :valid_time

  include PgSearch
  pg_search_scope :search, :against => [:title, :sport, :host_id, :venue, :details]
  pg_search_scope :with_trigram, :against => [:title, :sport, :host_id, :venue, :details], :using => :trigram
  pg_search_scope :with_dmetaphone, :against => [:title, :sport, :host_id, :venue, :details], :using => :dmetaphone
  pg_search_scope :with_ignoring_accents, :against => [:title, :sport, :host_id, :venue, :details], :ignoring => :accents

    def valid_time
      if start_time >= end_time
        self.errors.add :start_time, ' has to be before end time'
      end
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
    if @game.host_id != current_user.id
      redirect_to games_path
      flash[:alert] = "You cannot edit this game :P"
    end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @venues = Venue.find(:all)
    @selected_venue = @venues[1]
    @game.host_id = current_user.id

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    if @game.host_id != current_user.id
      redirect_to games_path
      flash[:alert] = "You cannot edit this game :P"
    else
      @game.destroy
      respond_to do |format|
        format.html { redirect_to games_url }
        format.json { head :no_content }
      end
    end
  end

  def join
    # Game.find(params[:id]).users.create({user_id: current_user.id})
    @member = GamesUsers.new 
    @member.user_id = current_user.id
    @member.game_id = params[:id]
    @member.save  
    respond_to do |format|
      format.html { redirect_to game_path(params[:id]) }
      format.json { head :no_content }
    end
  end

  def unjoin
    current_user.games.delete(Game.find(params[:id]))
    respond_to do |format|
      format.html { redirect_to game_path(params[:id]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row-fluid">
    <div class="span4">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="span4">
      <%= f.label :sport %>
      <%= select(:game, :sport_id, Sport.all.collect {|f| [f.name, f.id]}) %>
    </div>
    <div class="span4">
      <%= f.label :host_name %>
      <%= f.text_field :host_name, disabled: true, value: name(current_user.id) %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span4" id="date_select">
      <%= f.label :date %>
      <%= f.date_select :date %>
    </div>
    <div class="span4" id="time_select">
      <%= f.label :start_time %>
      <%= f.time_select :start_time, time_separator: ""%>
    </div>
    <div class="span4" id="time_select">
      <%= f.label :end_time %>
      <%= f.time_select :end_time, time_separator: "" %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span4">
      <%= f.label :venue_id %>
      <%= select(:game, :venue_id, Venue.all.collect {|f| [f.name, f.id]}) %>
    </div>
    <div class="span2">
      <%= f.label :maxpax %>
      <%= f.number_field :maxpax %>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span4">
        <%= f.label :details %>
        <%= f.text_area :details, cols: "50", rows: "60" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table class="table table-hover">
    <thead>
  <tr>
    <th>Name</th>
    <th>Host</th>
    <th>Sport</th>
    <th>Date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Venue</th>
    <th>Maxpax</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @games.each do |game| %>
  <tr>
    <td><%= game.title %></td>
    <td><%= name(User.find(game.host_id).id) %></td>    
    <td><%= game.sport.name %></td>
    <td><%= game.date %></td>
    <td><%= game.start_time.strftime("%H:%M") %></td>
    <td><%= game.end_time.strftime("%H:%M") %></td>
    <td><%= game.venue.name %></td>
    <td><%= game.maxpax %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Game', new_game_path, class: "btn" %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="row-fluid">
  <div class="span6"><h2>
  <%= @game.title %>
</h2>

<p>
  <b>Sport:</b>
  <%= @game.sport.name %>
</p>

<p>
  <b>Date:</b>
  <%= @game.date %>
</p>

<p>
  <b>Start time:</b>
  <%= @game.start_time.strftime("%H:%M")%>
</p>

<p>
  <b>End time:</b>
  <%= @game.end_time.strftime("%H:%M") %>
</p>

<p>
  <b>Venue:</b>
  <%= @game.venue.name %>
</p>

<p>
  <b>Details:</b>
  <%= @game.details %>
</p>

<p>
  <b>Maxpax:</b>
  <%= @game.maxpax %>
</p>

<p>
  <b>Host:</b>
  <%= name(User.find(@game.host_id).id) %>
</p>
</div>
  <div class="span6">
    <h2>Current Members</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Members (<%= @game.users.count.to_s + "/" + @game.maxpax.to_s %>)</th>
        </tr>
      </thead>
      <tbody>
        <% @game.users.each do|t| %>
          <tr><td><%= name(t) %></td></tr>
        <% end %>
      </tbody>
    </table>

    <% if GamesUsers.where(game_id: params[:id]).where(user_id: current_user.id).present? %>
    <%= link_to "Leave", leave_path, class: "btn btn-primary"%> 
    <% else %>
    <%= link_to "Join", join_path, class: "btn btn-primary"%> 
    <% end %>

    <%= link_to 'Edit', edit_game_path(@game), class: "btn btn-warning"%> 
    <%= link_to 'Back', games_path, class: "btn"%>

  </div>
</div>